version: '2'
services:
    artemis-app:
        image: artemis
        external_links:
            - artemis-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/artemis?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    artemis-mysql:
        extends:
            file: mysql.yml
            service: artemis-mysql
