version: '2'
services:
    artemis-mysql:
        container_name: artemis-mysql
        image: mysql:5.7.12
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=exerciseapplication
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
